// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sensor/sensor.proto

package sensor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestMessage string                 `protobuf:"bytes,1,opt,name=request_message,json=requestMessage,proto3" json:"request_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_sensor_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_sensor_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorRequest) GetRequestMessage() string {
	if x != nil {
		return x.RequestMessage
	}
	return ""
}

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      int32                  `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Temperature   int32                  `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_sensor_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_sensor_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *SensorData) GetSensorId() int32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *SensorData) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgTemp       float32                `protobuf:"fixed32,1,opt,name=avg_temp,json=avgTemp,proto3" json:"avg_temp,omitempty"`
	MaxTemp       float32                `protobuf:"fixed32,2,opt,name=max_temp,json=maxTemp,proto3" json:"max_temp,omitempty"`
	MinTemp       float32                `protobuf:"fixed32,3,opt,name=min_temp,json=minTemp,proto3" json:"min_temp,omitempty"`
	Sensors       []*SensorData          `protobuf:"bytes,4,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Err           string                 `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_sensor_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_sensor_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SensorResponse) GetAvgTemp() float32 {
	if x != nil {
		return x.AvgTemp
	}
	return 0
}

func (x *SensorResponse) GetMaxTemp() float32 {
	if x != nil {
		return x.MaxTemp
	}
	return 0
}

func (x *SensorResponse) GetMinTemp() float32 {
	if x != nil {
		return x.MinTemp
	}
	return 0
}

func (x *SensorResponse) GetSensors() []*SensorData {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *SensorResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_sensor_sensor_proto protoreflect.FileDescriptor

const file_sensor_sensor_proto_rawDesc = "" +
	"\n" +
	"\x13sensor/sensor.proto\"8\n" +
	"\rSensorRequest\x12'\n" +
	"\x0frequest_message\x18\x01 \x01(\tR\x0erequestMessage\"K\n" +
	"\n" +
	"SensorData\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x05R\bsensorId\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x05R\vtemperature\"\x9a\x01\n" +
	"\x0eSensorResponse\x12\x19\n" +
	"\bavg_temp\x18\x01 \x01(\x02R\aavgTemp\x12\x19\n" +
	"\bmax_temp\x18\x02 \x01(\x02R\amaxTemp\x12\x19\n" +
	"\bmin_temp\x18\x03 \x01(\x02R\aminTemp\x12%\n" +
	"\asensors\x18\x04 \x03(\v2\v.SensorDataR\asensors\x12\x10\n" +
	"\x03err\x18\x05 \x01(\tR\x03err2:\n" +
	"\x06Sensor\x120\n" +
	"\rGetSensorData\x12\x0e.SensorRequest\x1a\x0f.SensorResponseB/Z-github.com/biaferre/gprc-sensor-server/sensorb\x06proto3"

var (
	file_sensor_sensor_proto_rawDescOnce sync.Once
	file_sensor_sensor_proto_rawDescData []byte
)

func file_sensor_sensor_proto_rawDescGZIP() []byte {
	file_sensor_sensor_proto_rawDescOnce.Do(func() {
		file_sensor_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_sensor_proto_rawDesc), len(file_sensor_sensor_proto_rawDesc)))
	})
	return file_sensor_sensor_proto_rawDescData
}

var file_sensor_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sensor_sensor_proto_goTypes = []any{
	(*SensorRequest)(nil),  // 0: SensorRequest
	(*SensorData)(nil),     // 1: SensorData
	(*SensorResponse)(nil), // 2: SensorResponse
}
var file_sensor_sensor_proto_depIdxs = []int32{
	1, // 0: SensorResponse.sensors:type_name -> SensorData
	0, // 1: Sensor.GetSensorData:input_type -> SensorRequest
	2, // 2: Sensor.GetSensorData:output_type -> SensorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sensor_sensor_proto_init() }
func file_sensor_sensor_proto_init() {
	if File_sensor_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_sensor_proto_rawDesc), len(file_sensor_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_sensor_proto_goTypes,
		DependencyIndexes: file_sensor_sensor_proto_depIdxs,
		MessageInfos:      file_sensor_sensor_proto_msgTypes,
	}.Build()
	File_sensor_sensor_proto = out.File
	file_sensor_sensor_proto_goTypes = nil
	file_sensor_sensor_proto_depIdxs = nil
}
